/*
 * File: app/view/AttributField.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AttributField', {
    extend: 'Ext.form.FieldSet',

    requires: [
        'Ext.form.FieldContainer',
        'Ext.form.field.ComboBox'
    ],

    title: 'Type of analysis',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldcontainer',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            flex: 1,
                            labelAlign: 'top',
                            name: 'attribute',
                            allowBlank: false,
                            emptyText: 'Field',
                            editable: false,
                            store: [
                                [
                                    'run1',
                                    'Avg run1'
                                ],
                                [
                                    'activity',
                                    'Activity'
                                ],
                                [
                                    'count',
                                    'Count'
                                ]
                            ]
                        },
                        {
                            xtype: 'combobox',
                            flex: 1,
                            labelAlign: 'top',
                            name: 'border',
                            allowBlank: false,
                            emptyText: 'Type',
                            editable: false,
                            store: [
                                [
                                    'avgadmin',
                                    'Admin borders'
                                ],
                                [
                                    'avgzone',
                                    'Zones'
                                ]
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});