/*
 * File: app/view/StandardForm.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.StandardForm', {
    extend: 'Ext.form.Panel',

    requires: [
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox'
    ],

    border: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldset',
                    title: 'Periode',
                    items: [
                        {
                            xtype: 'datefield',
                            anchor: '100%',
                            fieldLabel: '',
                            labelAlign: 'top',
                            name: 'startdate',
                            allowBlank: false,
                            emptyText: 'Start date',
                            format: 'Y-m-d'
                        },
                        {
                            xtype: 'datefield',
                            anchor: '100%',
                            fieldLabel: '',
                            labelAlign: 'top',
                            name: 'enddate',
                            allowBlank: false,
                            emptyText: 'End date',
                            format: 'Y-m-d'
                        }
                    ]
                },
                {
                    xtype: 'fieldset',
                    title: 'Filter',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: '',
                            labelAlign: 'top',
                            name: 'categoryid',
                            emptyText: 'Category',
                            displayField: 'name',
                            store: 'Category',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: '',
                            labelAlign: 'top',
                            name: 'clientid',
                            emptyText: 'Client',
                            displayField: 'name',
                            store: 'Client',
                            valueField: 'id'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: '',
                            labelAlign: 'top',
                            name: 'groupid',
                            emptyText: 'Group',
                            displayField: 'name',
                            store: 'Group',
                            valueField: 'id'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});